services:
  php:
    build: docker/php
    command: bash -c "php -S 0.0.0.0:8080 -t /app/public"
    user: "1000:1000"
    ports:
        - 8080:8080
    volumes:
        - ".:/app"

  mariadb:
    container_name: db
    image: mariadb:11.4
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./migration/:/migration"
      # If not working create a .env with MARIADB_VOLUME=value
      - ${MARIADB_VOLUME}:/var/lib/mysql

volumes:
  mariadb_data:
