services:
  php:
    build: .
    ports:
        - 8080:80

  mariadb:
    container_name: db
    image: mariadb:11.4
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ${MARIADB_VOLUME:-mariadb_data}:/var/lib/mysql
      - ./migration:/docker-entrypoint-initdb.d

volumes:
  mariadb_data:
